name: VPC_Create_Dev

permissions:
  id-token: write
  contents: read
# on push
#on:
  #push:
   # branches:
    #  - main
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Auth to Google Cloud via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/833211051492/locations/global/workloadIdentityPools/oidc-pool/providers/oidc-provider"
          service_account: "oidc-sa@oidc-test-468417.iam.gserviceaccount.com"
          token_format: "access_token"
          create_credentials_file: true
      - name: authentication info display
        run: printenv 
      - name: Run API check script
      - name: Read Project ID from dev.tfvars
        id: vars
        run: |
          PROJECT_ID=$(grep -E '^project_id' dev.tfvars | awk -F'=' '{print $2}' | tr -d ' "')
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
        run: |
          chmod +x ./check-apis.sh
          ./check-apis.sh $PROJECT_ID

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init 
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars
      - name: Terraform apply
        run: terraform apply -var-file=dev.tfvars -auto-approve       

      # Optional:
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
