name: VPC_Create_PROD

permissions:
  id-token: write
  contents: read
# on push
#on:
  #push:
   # branches:
    #  - main
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Auth to Google Cloud via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/240233069147/locations/global/workloadIdentityPools/automation-oidc-pool/providers/automation-oidc-provider"
          service_account: "terraform-SA@cicd-prod-468221.iam.gserviceaccount.com"
          token_format: "access_token"
          create_credentials_file: true
      - name: authentication info display
        run: printenv 
      - name: Run API check script
        run: |
          chmod +x ./check-apis.sh
          ./check-apis.sh cicd-prod-468221

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init 
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=prod.tfvars
      - name: Terraform apply
        run: terraform apply -var-file=prod.tfvars -auto-approve       

      # Optional:
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
